version: '3.4'

services:
  app:
    image: back
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - mysql
    env_file:
      - .env
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"